services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: avg
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ""
    ports:
      - "5432:5432"
  user-service:
    image: user-service:latest
    ports:
      - "8081:8081"
    depends_on:
      - postgres
  company-service:
    image: company-service:latest
    ports:
      - "8082:8082"
    depends_on:
      - postgres
  eureka-server:
    image: eureka-server:latest
    ports:
      - "8761:8761"
  config-server:
    image: config-server:latest
    ports:
      - "8888:8888"
  gateway:
    image: gateway:latest
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
      - user-service
      - company-service