services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network
  config-server:
    build:
      context: ./config-server
    image: config-server:latest
    ports:
      - "8888:8888"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8888/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - app-network
  user-service:
    build:
      context: ./user-service
    image: user-service:latest
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/avg
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: ""
    networks:
      - app-network
  company-service:
    build:
      context: ./company-service
    image: company-service:latest
    ports:
      - "8082:8082"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/company
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: ""
    networks:
      - app-network
  eureka-server:
    build:
      context: ./eureka-server
    image: eureka-server:latest
    ports:
      - "8761:8761"
    networks:
      - app-network
  gateway:
    build:
      context: ./gateway
    image: gateway:latest
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
      - user-service
      - company-service
      - config-server
    networks:
      - app-network

networks:
  app-network:
    name: avb_test_app-network
    driver: bridge

volumes:
  postgres-data: