spring:
  application:
    name: company-service
  datasource:
    url: jdbc:postgresql://postgres:5432/avg
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
