spring:
  application:
    name: company-service
  datasource:
    url: jdbc:postgresql://avg-db:5432/avg
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
