spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: to-company
          uri: lb://company-service
          predicates:
            - Path=/company/**
        - id: to-user
          uri: lb://user-service
          predicates:
            - Path=/user/**

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
