spring:
  application:
    name: gateway
  config:
    import: configserver:http://config-server:8888
  cloud:
    gateway:
      routes:
        - id: to-company
          uri: lb://company-service
          predicates:
            - Path=/company/**
        - id: to-user
          uri: lb://user-service
          predicates:
            - Path=/user/**

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/