server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Natalya-Talalova/AVB_TEST.git
          search-paths: config-repo
          default-label: main

